spring.application.name=applicationProcessing
spring.datasource.url=jdbc:postgresql://localhost:5432/applicationProcessing
spring.datasource.username=postgres
spring.datasource.password=5266752465e

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true